### ISSUE TITLE
support Python 3

### ISSUE THREAD

**Issue by zenogantner** [hpclab/rankeval#2]
Do you have plans to support Python 3?
Would you be interested in pull requests that move the project closer to supporting Python 3?

**Comment by strani** [comment]
We are already working on the python3 support. In a few days, I will push a branch with the first attempt to provide such support. I will then notify you. Feedbacks and support will be highly appreciated.

**Comment by strani** [comment]
I pushed a branch (py3) with the preliminary attempt to support python3. The branch is in sync with the develop branch.

Unit tests are passing, but a deeper investigation is needed in order to establish if everything works as expected. Could you test it, suggesting fixes and improving reliability?

**Comment by zenogantner** [comment]
Great, will have a look at it on Monday.

**Comment by zenogantner** [comment]
When running my script, I get

```
[LightGBM] [Fatal] Sum of query counts is not same with #data
Traceback (most recent call last):
  File "./ranking-eval.py", line 106, in <module>
    model, model_description = train_lightgbm_model(args, dataset=train)
  File "./ranking-eval.py", line 32, in train_lightgbm_model
    scikit_model.fit(dataset.X, dataset.y, group=query_len)
  File "/usr/local/lib/python3.5/dist-packages/lightgbm/sklearn.py", line 474, in fit
    callbacks=callbacks)
  File "/usr/local/lib/python3.5/dist-packages/lightgbm/engine.py", line 183, in train
    booster = Booster(params=params, train_set=train_set)
  File "/usr/local/lib/python3.5/dist-packages/lightgbm/basic.py", line 1307, in __init__
    train_set.construct().handle,
  File "/usr/local/lib/python3.5/dist-packages/lightgbm/basic.py", line 860, in construct
    categorical_feature=self.categorical_feature, params=self.params)
  File "/usr/local/lib/python3.5/dist-packages/lightgbm/basic.py", line 728, in _lazy_init
    self.set_group(group)
  File "/usr/local/lib/python3.5/dist-packages/lightgbm/basic.py", line 1152, in set_group
    self.set_field('group', group)
  File "/usr/local/lib/python3.5/dist-packages/lightgbm/basic.py", line 986, in set_field
    ctypes.c_int(type_data)))
  File "/usr/local/lib/python3.5/dist-packages/lightgbm/basic.py", line 49, in _safe_call
    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: Sum of query counts is not same with #data
```

**Comment by strani** [comment]
Is `query_len` obtained with `dataset.get_query_size()`?
I have a similar script that do not uses the scikit-learn API but the proprietary API and works like a charm.

**Comment by strani** [comment]
I just tested the following snippet of code, and it works as expected:

`from rankeval.dataset import Dataset
import lightgbm as lgb

dataset =  Dataset.load(dataset_path)

lgb_model = lgb.LGBMModel(
    boosting_type='gbdt', 
    num_leaves=31, 
    learning_rate=0.05, 
    n_estimators=100, 
    objective='lambdarank'
)

lgb_model.fit(
    dataset.X, 
    dataset.y,
    group=dataset.get_query_size()
)
`

**Comment by zenogantner** [comment]
Do you mean get_query_sizes() (note the "s" at the end)?

It now does work like a charm, even with the scikit-learn API.

**Comment by strani** [comment]
Yes, I was missing an "s" in the copy-edit (fixed now). 
BTW, I'll close the two issues.

**Comment by zenogantner** [comment]
I found another issue:
```
> python3 ./ranking-eval.py --data-file candgen-score --model random --random-seed=1
random model
  metric train test
   MAP@1 1.000 1.000
   MAP@2 0.971 0.974
   MAP@3 0.949 0.956
   MAP@4 0.925 0.947
   MAP@5 0.901 0.916
   MRR@5 0.071 0.057
  NDCG@5 0.070 0.054
     R@1 0.023 0.017
     R@5 0.106 0.084

> python2 ./ranking-eval.py --data-file candgen-score --model random --random-seed=1
random model
  metric train test
   MAP@1 0.032 0.027
   MAP@2 0.025 0.020
   MAP@3 0.020 0.016
   MAP@4 0.017 0.013
   MAP@5 0.015 0.012
   MRR@5 0.071 0.057
  NDCG@5 0.070 0.054
     R@1 0.023 0.017
     R@5 0.106 0.084
```

There is something wrong with the MAP implementation on Python 3 (note I installed it from the py3 branch, vs. the default branch which I used for the Python 2 installation).

**Comment by zenogantner** [comment]
I have updated my Python 2 installation, can confirm the MAP bug there as well.

**Comment by strani** [comment]
I checked both py2 and py3 versions and they are correct. I introduced also an additional test case for the map metric given I was spending time there and fixed a problem with a test of a Jforest proxy not previously tested.

I could only suggest you to check that everything is in sync with the repo. I usually prefer installing rankeval with `pip install -e .[develop]` so that every modification made to the library (even a simple git pull) would automatically be seen by python.
