### ISSUE TITLE
Problem with Python 3.6

### ISSUE THREAD

**Issue by zenogantner** [hpclab/rankeval#6]
When installing from Github (either via setup.py, or pip3), I get the following error when trying to import anything from rankeval:

```
Traceback (most recent call last):
  File "./ranking-eval.py", line 10, in <module>
    from rankeval.analysis.effectiveness import query_class_performance
  File "/usr/local/lib/python3.6/dist-packages/rankeval/__init__.py", line 11, in <module>
    encoding='utf-8').read().strip()
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/rankeval/../VERSION'
```

Looking at /usr/local/lib/python3.6/dist-packages/, there is no VERSION (and there should not be, of course).  Note that in the source tree, the VERSION file *is* present in the parent directory of __init__.py.

**Comment by zenogantner** [comment]
Moving VERSION to the rankeval/ directory and adapting the paths in __init__.py and setup.py fixes the problem for me.
Let me know if you are interested in a pull request.

**Comment by strani** [comment]
The PR will be very welcome 👍 
Thank you!

**Comment by zenogantner** [comment]
Here it is: #8

Sorry for the delay.

**Comment by zenogantner** [comment]
By way, my colleague had the same problem with Python 2.7. Looking at the code, I do not think this ever worked for an installed rankeval.
